version: '3.8'

services:
  nginx:
    extends:
      file: ./docker/services-common.yml
      service: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${NGINX_SERVER_NAME}`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    depends_on:
      - php
  mysql:
    extends:
      file: ./docker/services-common.yml
      service: mysql
  php:
    extends:
      file: ./docker/services-common.yml
      service: php
    depends_on:
      - mysql

volumes:
  mysql:

networks:
  default:
    external:
      name: traefik-network
