version: '3.8'

services:
  nginx:
    extends:
      file: ./docker/services-common.yml
      service: nginx
    volumes:
      - ./code:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/servers:/docker-entrypoint.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${NGINX_SERVER_NAME}`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    depends_on:
      - php
  mysql:
    extends:
      file: ./docker/services-common.yml
      service: mysql
    volumes:
      - mysql:/var/lib/mysql
  php:
    extends:
      file: ./docker/services-common.yml
      service: php
    volumes:
      - ./code:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql:

networks:
  default:
    external:
      name: traefik-network
