version: '3.8'

services:
  nginx:
    extends:
      file: ./docker/services-common.yml
      service: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - php
  mysql:
    extends:
      file: ./docker/services-common.yml
      service: mysql
  php:
    extends:
      file: ./docker/services-common.yml
      service: php
    depends_on:
      - mysql

volumes:
  mysql:
