version: '3.8'

services:
  composer:
    image: composer:latest
    volumes:
      - ./code:/app
    networks:
      - default
      - traefik
  wp:
    extends:
      file: ./docker/services-common.yml
      service: wp
    networks:
      - default
      - traefik
  wordmove:
    extends:
      file: ./docker/services-common.yml
      service: wordmove
    networks:
      - default
      - traefik

networks:
  traefik:
    external:
      name: traefik-network
