version: '3.8'

services:
  composer:
    image: composer:latest
    volumes:
      - ./code:/var/www/html
  wordmove:
    extends:
      file: ./docker/services-common.yml
      service: wordmove
    volumes:
      - ./code:/var/www/html
      - ${SSH_PATH}:/wordmove/.ssh
