apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bedrock-project.fullname" . }}
  labels:
    {{- include "bedrock-project.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bedrock-project.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bedrock-project.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bedrock-project.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-wordpress
          image: {{ include "bedrock-project.imageName" .Values.wordpress.image }}
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          ports:
            - name: wordpress
              containerPort: {{ .Values.wordpress.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: application
            - mountPath: /var/www/html/web/app/uploads
              name: uploads
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secrets
                  key: mariadb-password
          envFrom:
            - configMapRef:
                name: {{ include "bedrock-project.fullname" . }}-wp-config
        - name: {{ .Chart.Name }}-nginx
          image: {{ include "bedrock-project.imageName" .Values.nginx.image }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: nginx
              containerPort: {{ .Values.nginx.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: application
            - mountPath: /var/www/html/web/app/uploads
              name: uploads
            - mountPath: /etc/nginx/conf.d/default.conf
              name: webserver-config
              subPath: nginx.conf
      initContainers:
        - name: init-application
          image: {{ include "bedrock-project.imageName" .Values.wordpress.image }}
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          command: [ "sh", "-c", "cp -r /var/www/html/* /entrypoint && chown www-data:www-data -R /entrypoint" ]
          volumeMounts:
            - name: application
              mountPath: /entrypoint
            - name: uploads
              mountPath: /var/www/html/web/app/uploads
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: application
          emptyDir: {}
        - name: uploads
          {{- if .Values.uploadsPVC.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "bedrock-project.fullname" . }}-uploads
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: webserver-config
          configMap:
            name: {{ include "bedrock-project.fullname" . }}-nginx

