apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secrets
  labels:
    {{- include "bedrock-project.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | default (randAlphaNum 10) | b64enc | quote }}
  mariadb-replication-password: {{ .Values.mariadb.auth.replicationPassword | default (randAlphaNum 10) | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | default (randAlphaNum 10) | b64enc | quote }}
