apiVersion: v1
kind: Service
metadata:
  name: {{ include "bedrock-wordpress.fullname" . }}
  labels:
    {{- include "bedrock-wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bedrock-wordpress.selectorLabels" . | nindent 4 }}
---
{{- if not .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bedrock-wordpress.name" $ }}-db
  labels: {{- include "bedrock-wordpress.labels" $ | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.mariadb.host }}
{{- end }}
