version: '3.8'

x-db: &db-env
  DB_NAME: ${MYSQL_DATABASE}
  DB_USER: ${MYSQL_USER}
  DB_PASSWORD: ${MYSQL_PASSWORD}
  DB_PREFIX: ${MYSQL_PREFIX:-wp_}
  DB_HOST: mysql
x-wp: &wp-env
  WP_ENV: development
  WP_HOME: http://${NGINX_SERVER_NAME}
  WP_SITEURL: http://${NGINX_SERVER_NAME}/wp
  WP_DEBUG_LOG: ${WP_DEBUG_LOG:-/var/log/bedrock}

services:
  nginx:
    image: maiorano84/envinx
    ports:
      - "80"
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
      NGINX_ROOT: ${NGINX_ROOT}
    volumes:
      - ../code:/var/www/html
      - ../logs/nginx:/var/log/nginx
      - ./nginx:/docker-entrypoint.d
  mysql:
    image: mariadb:10.1
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION:-7.4}
    ports:
      - "9000"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=1"
      XDEBUG_MODE: "develop,debug,profile"
      <<: *db-env
      <<: *wp-env
    volumes:
      - ../code:/var/www/html
      - ../logs/bedrock:/var/log/bedrock
  wordmove:
    build:
      context: ./wordmove
      args:
        PHP_VERSION: ${PHP_VERSION:-7.4}
    environment:
      <<: *db-env
      <<: *wp-env
    volumes:
      - ../code:/var/www/html
      - ${SSH_PATH}:/wordmove/.ssh
  wp:
    image: wordpress:cli-php${PHP_VERSION:-7.4}
    environment:
      <<: *db-env
      <<: *wp-env
    volumes:
      - ../code:/var/www/html
    entrypoint: ["wp"]
