nameOverride: ""
fullnameOverride: ""

# VCL options
backend: {}
#  host:
#  port:

purgeWhitelist: []
#  - "127.0.0.1"
#  - "localhost"

# Service Options
service:
  enabled: true
  type: LoadBalancer
  port: 80

# Autoscaling options
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Deployment Options
image:
  repository: varnish
  pullPolicy: IfNotPresent
  tag: "6.6.1"

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
