apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "varnish.fullname" . }}-vcl
  labels: {{- include "varnish.labels" . | nindent 4 }}
data:
  default.vcl: |-
    {{- tpl (.Files.Get "config/varnish.vcl") . | nindent 4 }}
