nameOverride: ""
fullnameOverride: ""
replicaCount: 1

environment: development
hostName: &commonName localhost

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: LoadBalancer
  ports:
    http:
      port: 80
    wordpress:
      port: 9000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  #  - host: *commonName
  #    http:
  #      paths:
  #        - path: /
  #          pathType: ImplementationSpecific
  #          backend:
  #            service:
  #              name: example-bedrock-project-frontend
  #              port:
  #                name: http

  tls: []
  #  - secretName: bedrock-example-tls
  #    hosts:
  #      - *commonName

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

wordpress:
  image:
    repository: maiorano84/wordpress-bedrock
    pullPolicy: IfNotPresent
    tag: "latest"

nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "1.21.1-alpine"

mariadb:
  enabled: true
  # host: external.host.domain.com
  # prefix: wp_
  auth:
    database: bedrock
    username: bedrock
    # password: secret
    existingSecret: example-bedrock-project-mariadb-secrets

uploads:
  persist: false
  annotations: {}
    # helm.sh/resource-policy: keep
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
